name: Deploy - Backend CD - Azure App Service

on:
  # This will trigger only on pushes to main (including PR merges)
  push:
    branches: [ "main" ]
  # Manual triggering option
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY_BACKEND }}
  CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME_BACKEND }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  APP_SERVICE_NAME: ${{ secrets.AZURE_APP_SERVICE_NAME_BACKEND }}

jobs:
  build:
    # This ensures the job only runs on pushes to main (which includes PR merges)
    # and not on PR open/update events
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout'
        uses: actions/checkout@main

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_REGISTRY_BACKEND_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_BACKEND_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/server
          push: true
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:latest
          cache-to: type=inline

  deploy:
    needs: build
    # Ensure deploy job only runs when build job runs
    # if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          slot-name: 'production'

